server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    healthcheck:
        enabled: true                             # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
